ENH: Upgrade visualizer to use q2templates
qiime2/cookiecutter-plugin-template pull request #7
Opened 2016-10-29 00:00 UTC by jakereps

Upgrades example visualizer to utilize `q2templates`.

2016-11-01 18:30 UTC, thermokarst requested changes
Thanks @jakereps! A few minor comments and then this is GTG

2016-11-01 18:30 UTC, thermokarst commented on {{cookiecutter.distribution_name}}/{{cookiecutter.package_name}}/_dummy_visualizer.py
> +        "mapping1": df1.to_html(index=False, classes='dummy-class'),
Most/all of the other visualizations with a table included have something along the following lines, in order to format the HTML table correctly:

```python
table = d1.to_html(index=False, classes="table table-striped table-hover")
table = table.replace('border="1"', 'border="0"')
```

Can you add that for both of the tables in this viz?

2016-11-01 18:30 UTC, thermokarst commented on {{cookiecutter.distribution_name}}/{{cookiecutter.package_name}}/assets/index.html
> +{% block head %}
I think we can drop all of this `{% block head %}` section once the table is bootstrappin

2016-11-01 18:30 UTC, thermokarst commented on {{cookiecutter.distribution_name}}/{{cookiecutter.package_name}}/assets/index.html
> +    <h3>mapping1:</h3>
Can you stick these into a two-col grid layout? That way folks who might not be familiar with bootstrap can see that feature in action.

2016-11-02 02:23 UTC, jakereps commented
Thanks @thermokarst, should be good to go 👍 !

2016-11-02 12:18 UTC, thermokarst approved these changes

2016-11-02 12:18 UTC, merged